-- 食品検索・登録コスト計測用イベントログ
CREATE TABLE IF NOT EXISTS food_registration_events (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  meal_entry_id INT UNSIGNED NULL,
  recorded_on DATE NOT NULL,
  meal_type VARCHAR(20) NOT NULL,
  raw_input VARCHAR(255) NULL,
  selected_food_name VARCHAR(255) NOT NULL,
  food_id INT UNSIGNED NULL,
  selected_source VARCHAR(50) NOT NULL,
  calorie_source_saved VARCHAR(50) NULL,
  search_started_at DATETIME NULL,
  saved_at DATETIME NOT NULL,
  duration_ms INT UNSIGNED NULL,
  candidate_count INT UNSIGNED NULL,
  selected_candidate_rank INT UNSIGNED NULL,
  calories_before_edit INT NULL,
  calories_saved INT NOT NULL,
  calories_edited TINYINT(1) NOT NULL DEFAULT 0,
  used_alias TINYINT(1) NOT NULL DEFAULT 0,
  used_local_db TINYINT(1) NOT NULL DEFAULT 0,
  used_brave TINYINT(1) NOT NULL DEFAULT 0,
  used_claude_estimate TINYINT(1) NOT NULL DEFAULT 0,
  used_claude_web_search TINYINT(1) NOT NULL DEFAULT 0,
  web_search_count_delta INT NOT NULL DEFAULT 0,
  error_type VARCHAR(100) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_fre_user_saved (user_id, saved_at),
  INDEX idx_fre_source (selected_source),
  INDEX idx_fre_recorded_on (user_id, recorded_on)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
