-- AIコーチ用の日次栄養サマリー
CREATE TABLE IF NOT EXISTS daily_nutrition_summaries (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  recorded_on DATE NOT NULL,
  total_kcal INT NOT NULL DEFAULT 0,
  total_protein_g DECIMAL(10, 2) NULL,
  total_fat_g DECIMAL(10, 2) NULL,
  total_carbs_g DECIMAL(10, 2) NULL,
  total_fiber_g DECIMAL(10, 2) NULL,
  total_sodium_mg DECIMAL(12, 2) NULL,
  breakfast_kcal INT NOT NULL DEFAULT 0,
  lunch_kcal INT NOT NULL DEFAULT 0,
  dinner_kcal INT NOT NULL DEFAULT 0,
  snack_kcal INT NOT NULL DEFAULT 0,
  meal_entry_count INT NOT NULL DEFAULT 0,
  estimated_entry_count INT NOT NULL DEFAULT 0,
  edited_entry_count INT NOT NULL DEFAULT 0,
  low_confidence_entry_count INT NOT NULL DEFAULT 0,
  ai_web_search_entry_count INT NOT NULL DEFAULT 0,
  user_registered_entry_count INT NOT NULL DEFAULT 0,
  pfc_known_entry_count INT NOT NULL DEFAULT 0,
  top_foods_json JSON NULL,
  summary_text TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_dns_user_date (user_id, recorded_on),
  INDEX idx_dns_user_recorded (user_id, recorded_on)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
